### ISSUE TITLE
Making the workflow robust to differences in acquisition protocols

### ISSUE THREAD

**Issue by craigmoodie** [poldracklab/preprocessing-workflow#1]
[i] Right now the preprocessing workflow can only handle inputs from workflows that follow the HCP scanning protocol. However, most studies and especially older studies, will have utilize a traditional double echo fieldmap approach. Hence, the workflow needs to be able to handle both approaches.

[ii] It would also be good to test different types of fieldmaps, such as GRE, SE and spiral fieldmaps.

[iii] Lastly, it would be good to build in a contingency for when a protocol has no fieldmaps, or when fieldmaps are missing for some subjects.

**Comment by vsoch** [comment]
@craigmoodie look at you, Github pro! *so proud*

**Comment by craigmoodie** [comment]
thanks @vsoch! :+1:

**Comment by oesteban** [comment]
So let's make a nipype pro from a Github pro:
[i] Added #20.
[ii] Added #20 and #21.
[iii] Added #19.

@craigmoodie, Do these cover all the defined use-cases?

**Comment by craigmoodie** [comment]
Hi Osteban, there is also the case where the user will inputs two phase-encoding reversed spin-echo field maps, but this is already implemented in the original workflow that I uploaded. Otherwise, I think those issues should cover all of the other use cases.

**Comment by oesteban** [comment]
Cool. Yes, that is the default use-case as you initially implemented it. Actually, that should exactly correspond to this new workflow: https://github.com/poldracklab/preprocessing-workflow/blob/master/fmriprep/workflows/fieldmap.py#L15. For this reason I did not open any other ticket.

Now that this issue is mapped to the 3 elementary tasks (#19, #20 and #21) I will close it.

Thanks for reporting!
