### ISSUE TITLE
Create test dataset of subsampled images

### ISSUE THREAD

**Issue by oesteban** [poldracklab/preprocessing-workflow#104]
Create a dataset and downsample it to implement smoke tests. This small dataset would include one subject from ds005 (no fieldmaps), one subject from HCP in which only the multiple-SEs fieldmaps is found (multiple-SEs fieldmaps) and one subject from HCP in which only the magnitude&phase fieldmaps are found (two-GRE fieldmaps).

**Comment by suyashdb** [comment]
@oesteban - i have copied two datasets to '/corral-repl/utexas/poldracklab/openfmri/test_datsets_hcp/'.

ds 0005 - No fieldmaps
ds054 - magnitude&phase fieldmaps are found (two-GRE fieldmaps)
HCP - In process (4: Multiple phase encoded directions)

**Comment by suyashdb** [comment]
@oesteban @chrisfilo 
Looks like there is naming nomenclature issue in hcp/fmaps .. 
If i take - LR as index - 01
RL as index - 02
and latter LR/RL in filename is encoded in .json as -i, +i .. Event then two diff fmap files will have same name as follows -

rfMRI_REST1_LR_285345_3T_SpinEchoFieldMap_LR.nii.gz ->  sub-285345_dir-01_epi.nii.gz

rfMRI_REST1_LR_285345_3T_SpinEchoFieldMap_RL.nii.gz -> sub-285345_dir-01_epi.nii.gz

There .json file will have filed intended for field pointing to two diff func-files but how can we have fmap files with same name...?

**Comment by suyashdb** [comment]
I am using case 4 for fmap naming under BIDS Std:
8.9.4 Case 4: Multiple phase encoded directions (topup)

fmap/sub<label>[_acq<label>]_dir<index>_epi.nii[.gz]
fmap/sub<label>[_acq<label>]_dir<index>_epi.json

**Comment by oesteban** [comment]
rfMRI_REST1_LR_285345_3T_SpinEchoFieldMap_RL.nii.gz -> sub-285345_dir-0**2**_epi.nii.gz

**Comment by suyashdb** [comment]
then rfMRI_**REST2_LR**_285345_3T_SpinEchoFieldMap_RL.nii.gz -> sub-285345_dir-02_epi.nii.gz

**Comment by suyashdb** [comment]
The solution to this will be using the optional acq tag:
sub-285345_acq-REST1LR_dir-01_epi.nii.gz

But do you want that ..?

**Comment by oesteban** [comment]
ah ok, I see.

rfMRI_REST1_LR_285345_3T_SpinEchoFieldMap_LR.nii.gz -> sub-285345_dir-01_run-01_epi.nii.gz
rfMRI_REST1_LR_285345_3T_SpinEchoFieldMap_RL.nii.gz -> sub-285345_dir-02_run-01_epi.nii.gz
rfMRI_REST2_LR_285345_3T_SpinEchoFieldMap_LR.nii.gz -> sub-285345_dir-01_run-02_epi.nii.gz
rfMRI_REST2_LR_285345_3T_SpinEchoFieldMap_RL.nii.gz -> sub-285345_dir-02_run-02_epi.nii.gz

**Comment by suyashdb** [comment]
@oesteban Thanks for clarifying.. Even though 'run' key/value pair is not listed in BIDS/fmap, i can use it..?  Good to know..

**Comment by suyashdb** [comment]
After discussing with @chrisfilo:

sub-285345_dir-1_run-01_epi.nii.gz
...
sub-285345_dir-1_run-10_epi.nii.gz
(one run per task)

sub-285345_dir-2_run-01_epi.nii.gz
...
sub-285345_dir-2_run-10_epi.nii.gz

@chrisfilo will describe this use case in the spec draft

**Comment by suyashdb** [comment]
@chrisfilo: Looks like i still failed to explain the HCP case completely -
It looks as follows if i use above mentioned dir- and run-. Still menance of 
rfMRI_**REST1_LR**_285345_3T_SpinEchoFieldMap_**RL**.nii.gz  - sub-285345_**dir-01_run-01**_epi.nii.gz
rfMRI_REST1_LR_285345_3T_SpinEchoFieldMap_RL.nii.gz  - sub-285345_dir-01_run-02_epi.nii.gz
rfMRI_REST1_RL_285345_3T_SpinEchoFieldMap_LR.nii.gz  - sub-285345_dir-02_run-01_epi.nii.gz
rfMRI_REST1_RL_285345_3T_SpinEchoFieldMap_RL.nii.gz  - sub-285345_dir-02_run-02_epi.nii.gz
rfMRI_**REST2_LR**_285345_3T_SpinEchoFieldMap_**LR**.nii.gz  - sub-285345_**dir-01_run-01_**epi.nii.gz
rfMRI_REST2_LR_285345_3T_SpinEchoFieldMap_RL.nii.gz  - sub-285345_dir-01_run-02_epi.nii.gz
rfMRI_REST2_RL_285345_3T_SpinEchoFieldMap_LR.nii.gz  - sub-285345_dir-02_run-01_epi.nii.gz
rfMRI_REST2_RL_285345_3T_SpinEchoFieldMap_RL.nii.gz  - sub-285345_dir-02_run-02_epi.nii.gz

So the problem here is we are trying to describe 3 variables using two tags.

**Comment by suyashdb** [comment]
Third dataset is also under `/corral-repl/utexas/poldracklab/openfmri/test_datsets_hcp/`

**Comment by shoshber** [comment]
Even though this isn't totally done yet, is there one subject/run that is done so I can start working on https://github.com/poldracklab/preprocessing-workflow/issues/107 ?

**Comment by oesteban** [comment]
working on it right now...

**Comment by oesteban** [comment]
https://googledrive.com/host/0BxI12kyv2olZRHJucndFY1p6Tm8

**Comment by oesteban** [comment]
Updated the link before
